[build]
  publish = "public/"
  environment = { NODE_VERSION = "18." }

[[edge_functions]]
  function = "embed"
  path = "/embed"

[[edge_functions]]
  function = "archive"
  path = "/archive.warc.gz"

[[edge_functions]]
  function = "archive"
  path = "/archive.wacz"
